/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import DomainModel.Register;

/**
 *
 * @author Baransel
 */
public class AnaEkran extends javax.swing.JFrame {

    Register register = MainCenter.register;
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAracKiralama = new javax.swing.JButton();
        btnSubeAcma = new javax.swing.JButton();
        btnKampanyaDuzenleme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnAracKiralama.setText("Araç Kiralama");
        btnAracKiralama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAracKiralamaActionPerformed(evt);
            }
        });

        btnSubeAcma.setText("Şube Açma");
        btnSubeAcma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubeAcmaActionPerformed(evt);
            }
        });

        btnKampanyaDuzenleme.setText("Kampanya Düzenleme");
        btnKampanyaDuzenleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKampanyaDuzenlemeActionPerformed(evt);
            }
        });

        jButton1.setText("Şube Müdürü Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKampanyaDuzenleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubeAcma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAracKiralama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAracKiralama)
                .addGap(18, 18, 18)
                .addComponent(btnSubeAcma)
                .addGap(18, 18, 18)
                .addComponent(btnKampanyaDuzenleme)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAracKiralamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAracKiralamaActionPerformed
        if(Musteri.login) {
            new AracKiralamaEkran().setVisible(true);
        }else {
            new MusteriGiris().setVisible(true);
        }
    }//GEN-LAST:event_btnAracKiralamaActionPerformed

    private void btnSubeAcmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubeAcmaActionPerformed
        AdminLogin al = new AdminLogin();
        al.setSayfa(0);
        al.setVisible(true);
    }//GEN-LAST:event_btnSubeAcmaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminLogin al = new AdminLogin();
        al.setSayfa(1);
        al.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKampanyaDuzenlemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKampanyaDuzenlemeActionPerformed
        if(Mudur.login) {
            register.kampanyaBaslat();
            this.setVisible(false);
            new KampanyaDuzenlemeEkran().setVisible(true);
        }else {
            this.setVisible(false);
            new SubeMuduruLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnKampanyaDuzenlemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAracKiralama;
    private javax.swing.JButton btnKampanyaDuzenleme;
    private javax.swing.JButton btnSubeAcma;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
