/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import DomainModel.AracKiralama;
import DomainModel.Register;
import DomainModel.Sube;
import DomainModel.Tarih;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Baransel
 */
public class AracKiralamaEkran extends javax.swing.JFrame {
    Register register = MainCenter.register;
    DefaultComboBoxModel<String> modelAlisTarih,modelTeslimTarih;
    DefaultComboBoxModel<String> modelAlisSube,modelTeslimSube;
    String[] subeler;
    String[] tarihler;
    public AracKiralamaEkran() {
        subeleriAl();
        tarihleriAl();
        modelAlisTarih = new DefaultComboBoxModel<>(tarihler);
        modelTeslimTarih = new DefaultComboBoxModel<>(tarihler);
        modelAlisSube = new DefaultComboBoxModel<>(subeler);
        modelTeslimSube = new DefaultComboBoxModel<>(subeler);
        initComponents();
        lblHosgeldiniz.setText("Hoşgeldiniz " + Musteri.musteri.getIsim() + " " + Musteri.musteri.getSoyisim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHosgeldiniz = new javax.swing.JLabel();
        comboBoxAlisSube = new javax.swing.JComboBox();
        comboBoxTeslimSube = new javax.swing.JComboBox();
        comboBoxAlisTarih = new javax.swing.JComboBox();
        comboBoxTeslimTarih = new javax.swing.JComboBox();
        btnDevam = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setResizable(false);

        jLabel1.setText("Alış Şube");

        jLabel2.setText("Teslim Şube");

        jLabel3.setText("Teslim Tarih");

        jLabel4.setText("Alış Tarih");

        lblHosgeldiniz.setText("Hoşgeldiniz Bilmem KİM");

        comboBoxAlisSube.setModel(modelAlisSube);

        comboBoxTeslimSube.setModel(modelTeslimSube);

        comboBoxAlisTarih.setModel(modelAlisTarih);

        comboBoxTeslimTarih.setModel(modelTeslimTarih);

        btnDevam.setText("Devam");
        btnDevam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevamActionPerformed(evt);
            }
        });

        jButton1.setText("İptal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHosgeldiniz)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxAlisSube, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxTeslimSube, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxAlisTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnDevam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboBoxTeslimTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHosgeldiniz)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxAlisSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxTeslimSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxAlisTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxTeslimTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevam)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void subeleriAl() {
        subeler = new String[register.subeCatalog.getSubeler().size()];
        for (int i = 0;i<subeler.length;i++) {
            subeler[i] = register.subeCatalog.getSubeler().get(i).getSubeAdi();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDevamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevamActionPerformed
        DomainModel.Musteri musteri = Musteri.musteri;
        int gun = LocalDate.now().getDayOfMonth();
        int ay = LocalDate.now().getMonthValue();
        int yil = LocalDate.now().getYear();
        Tarih alisTarih = new Tarih(gun, ay, yil);alisTarih.tarihArttir(comboBoxAlisTarih.getSelectedIndex() + 1);
        Tarih teslimTarih = new Tarih(gun, ay, yil);teslimTarih.tarihArttir(comboBoxTeslimTarih.getSelectedIndex() + 1);
        Sube alisSube = register.subeCatalog.getSubeler().get(comboBoxAlisSube.getSelectedIndex());
        Sube teslimSube = register.subeCatalog.getSubeler().get(comboBoxTeslimSube.getSelectedIndex());
        AracKiralama ak = register.yeniKiralamaBaslat(musteri, alisSube, teslimSube, alisTarih, teslimTarih);
        if(register.araclariListele().size() > 0) {
            AracSecEkrani ase = new AracSecEkrani();
            ase.setAk(ak);
            ase.setUygunAraclar(register.araclariListele());
            ase.setVisible(true);
            this.setVisible(false);
        }else {
            JOptionPane.showMessageDialog(this, "Uygun araç bulunamadı. Kriterlerinizi değiştirin", "Araç Bulunamadı", 0);
        }
        
    }//GEN-LAST:event_btnDevamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AracKiralamaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AracKiralamaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevam;
    private javax.swing.JComboBox comboBoxAlisSube;
    private javax.swing.JComboBox comboBoxAlisTarih;
    private javax.swing.JComboBox comboBoxTeslimSube;
    private javax.swing.JComboBox comboBoxTeslimTarih;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblHosgeldiniz;
    // End of variables declaration//GEN-END:variables

    private void tarihleriAl() {
        tarihler = new String[120];
        int gun = LocalDate.now().getDayOfMonth();
        int ay = LocalDate.now().getMonthValue();
        int yil = LocalDate.now().getYear();
        Tarih tarih = new Tarih(gun, ay, yil);
        
        for(int i = 0;i<tarihler.length;i++) {
            tarih.tarihArttir(1);
            tarihler[i] = tarih.tarihYaz();
        }   
    }
}
